spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  liquibase:
    change-log: classpath:liquibase/changelog.xml
    password: ${JDBC_DATABASE_PASSWORD}
    url:  ${JDBC_DATABASE_URL}
    user: ${JDBC_DATABASE_USERNAME}
  http:
    enabled: true
    force: true
